### ISSUE TITLE
Screen Venture Fund investees

### ISSUE THREAD

**Issue by lacabra** [DPGAlliance/technical-roadmap#24]
Screen the following full submissions against the DPG Standard:
- [x] Avyantra Health Technologies #20
- [ ] Somleng from Chatterbox #21
- [ ] GeoMancer from Thinking Machines #22
- [ ] AI Powered Poverty Estimator from Thinking Machines #23

**Comment by lacabra** [comment]
The work planned for this Epic was done on our side. This has been blocked for more than two months because these projects do not meet the standard. We keep the individual tasks blocked, but we close this epic.
